name: Build and deploy to Firebase

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.2
    - run: npm install
    - run: npm run build
      env:
        CI: false
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build
      - uses: actions/checkout@v2
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        
